version: '3.8'

services:
  api:
    image: newsscraperapi-flask
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongo_data:/etc/mongo/

volumes:
  mongo_data:
